### 404 error
GET http://localhost:8000/route/neve/defined


###Login Route
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email": "ibromoh@gmail.com",
    "password": "test@123"
}

###Register Route
POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "firstName": "Ibrahim",
    "lastName": "Mohammed",
    "email": "ibromoh@gmail.com",
    "password": "test@123",
    "passwordConfirmation": "test@123"
}

# POSTS ROUTES
###Get all posts
GET http://localhost:8000/posts

###Get post by ID
GET http://localhost:8000/posts/606dc98d82dcab1a7c701c5

###Create a post
POST http://localhost:8000/posts/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2MDZkYjE4YmQ1Nzg5YjgxM2I1N2UwMGUiLCJpYXQiOjE2MTc4MDc3MzIsImV4cCI6MTYxNzgxMTMzMn0.rxBYXo0kU2I3exVk4iJzRT59wjkVwalNVhkkeiWxKEo

{
    "title": "My First Post",
    "body": "My first post body"
}